version: 2.1
workflows:
  Build monthly report:
    triggers:
      - schedule:
          cron: "0 0 1 * *" # At 00:00 on day-of-month 1. (UTC+0900)
          filters:
            branches:
              only:
                - main
    jobs:
      - monthly-report
jobs:
  monthly-report:
    docker:
      - image: sugarshin/cimg-base-nvm:2.0.0
    steps:
      - checkout
      - run:
          name: Setup nvm
          command: |
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo 'source "$NVM_DIR/nvm.sh" --no-use' >> $BASH_ENV
      - run:
          name: Install and use specific verion nodejs
          command: nvm install
      - run: sed -i -e 's/ --no-use//' $BASH_ENV
      - run: npm install --global yarn
      - run:
          name: System information
          command: |
            echo "Node.js: $(node -v)"
            echo "npm:     $(npm -v)"
            echo "Yarn:    $(yarn --version)"
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
          environment:
            YARN_CACHE_FOLDER: &YARN_CACHE_FOLDER ~/.cache/yarn
      - save_cache:
          paths:
            - *YARN_CACHE_FOLDER
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Configure Git
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 's+circleci@sugarshin.net'
      - run:
          command: /bin/bash monthly-report.sh
      - run:
          name: Notify
          command: |
            curl -XPOST -d '{"text": "Successfully monthly report published to blog.sugarshin.net"}' $SLACK_WEBHOOK_URL
